### ISSUE TITLE
Lint errors with custom twig tags

### ISSUE THREAD

**Issue by PhilETaylor** [VincentLanglet/Twig-CS-Fixer#114]
After installing https://github.com/buzzingpixel/twig-switch and using syntax like:

```twig
{% switch myVar %}
    {% case 'value1' %}
        {# ...code here to run for value1 #}
    {% case 'value2' %}
        {# ...code here to run for value2 #}
    {% default %}
        {# ...code here to run for default when no case matched #}
{% endswitch %}
```

The linter is now complaining it doesn't like the `switch` 

example: 
<img width="1018" alt="ScreenShot-2023-01-12-10 59 49" src="https://user-images.githubusercontent.com/400092/212049562-ac1e4d17-2e40-450e-a222-17bb3dbcdf80.png">

Is there any way to tell the linter that this is ok?

**Comment by VincentLanglet** [comment]
You'll need a custom config file.
Take a look at the https://github.com/VincentLanglet/Twig-CS-Fixer#token-parser section
you'll use the following code:
```
<?php

$config = new TwigCsFixer\Config\Config();
$config->addExtension(new SwitchTwigExtension());

return $config;
```

**Comment by PhilETaylor** [comment]
Awesome - thanks for the speedy reply. I'll take a look.

**Comment by PhilETaylor** [comment]
Works perfectly - once I upgraded to the latest version of course - doh - thanks again.

**Comment by VincentLanglet** [comment]
You're welcome. Feel free to star and share this repository if you like it ! :)

**Comment by PhilETaylor** [comment]
Done done and done. 

<img width="621" alt="ScreenShot-2023-01-12-11 13 31" src="https://user-images.githubusercontent.com/400092/212052318-fcaa0a38-c368-4992-83e4-82837f49bc28.png">
