### ISSUE TITLE
Convert Tab indention to spaces

### ISSUE THREAD

**Issue by alexander-schranz** [VincentLanglet/Twig-CS-Fixer#116]
### Rule(s) related to or rule(s) missing

I thought I create some rule requests which maybe could also be usable.

Why it maybe make sense to make this rule based on the outputted type e.g.:

```php
Indention([
    'docker-compose.yml.twig' => 2,
    '*.yaml.twig' => 4,
    '*.html.twig' => 4,
])
```

Based on this rule all indention should be divideable by 4 or 2 or the given number, but more required in my case would be convert tabs automatically to spaces when enabled.

maybe `Indention(4)` is also enough as for more complicated projects different `.twig-cs-fixer.php` can be created which match e.g. only `yaml.twig` and the other `html.twig` files.

### Expected behavior

All indention with tabs (maybe exclude tab characters elsewhere then beginning of the line?) should be converted to spaces based on the ruleset.

```diff
-	{{ test }}
+    {{ test }}
```

### Actual behavior

Such rule does not yet exist.

**Comment by VincentLanglet** [comment]
> maybe Indention(4) is also enough as for more complicated projects different .twig-cs-fixer.php can be created which match e.g. only yaml.twig and the other html.twig files.

I think indeed that's enough.

Does https://github.com/VincentLanglet/Twig-CS-Fixer/pull/117 works fine for you ? @alexander-schranz
