### ISSUE TITLE
Request: Force "include with ... only"

### ISSUE THREAD

**Issue by RobinHoutevelts** [VincentLanglet/Twig-CS-Fixer#118]
Hi, I stumbled upon this package while searching for a way to force `with ... only`.

Is it possible to somehow enforce this behavior?  
I'm wiling to write the sniffer myself, however I've never written one before so could use some guidance.

### Expected behavior

```diff
-{% include 'template.html' with {'foo': 'bar'} %}
+{% include 'template.html' with {'foo': 'bar'} only %}
```

### Reason

At my workplace we have a lot of templates and it becomes unclear where a used variable comes from.  
By forcing ourselves to use `with ... only` we hope to always leave a trail.

**Comment by VincentLanglet** [comment]
Hi, 
I'm not sure if it's possible.

First, a way to check if it's possible would be to write a temporary test like
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/7fdeb199af9903e9c1e24f6dec85eb66b0c32f69/tests/Token/Tokenizer/TokenizerTest.php#L18

With a file like https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/tests/Token/Tokenizer/Fixtures/test1.twig
but with the code 
```
{% include 'template.html' with {'foo': 'bar'} %}
{% include 'template.html' with {'foo': 'bar'} only %}
```

We'll be able to see how the Tokenizer transform this code.

Then, we'll need to implement a rule doing something like
- If `{%` is found
- Check it's related to `include`
- Find the next `%}`
- Check if the previous TEXT token is `only`

But adding automatically the `only` keyword might break some code ; so I wonder if we'll need to add a `risky` flag to such rules...
