### ISSUE TITLE
          >>   | File is invalid: Unexpected "component" tag (expecting closing tag for the "block" tag defined near line 6).  

### ISSUE THREAD

**Issue by allan-simon** [VincentLanglet/Twig-CS-Fixer#123]
Currently twig-cs-fixer does not support the tag "component" defined by  https://github.com/symfony/ux-twig-component

**Comment by VincentLanglet** [comment]
Hi, this can be solve manually on your project with this solution: https://github.com/VincentLanglet/Twig-CS-Fixer#token-parser

**Comment by VincentLanglet** [comment]
Hi, I tried both `{{ component('Alert', { message: 'Hello Twig Components!' }) }}` and
```
{% block content %}
    // the content will appear in here
{% endblock %}
```
 on my project and this work fine.

**Comment by VincentLanglet** [comment]
This can be solved manually by following https://github.com/VincentLanglet/Twig-CS-Fixer#token-parser
and writing
```
$config->addTwigExtension(new ComponentExtension());
```
or
```
$config->addTokenParser(new ComponentTokenParser());
```

Unfortunately, unlike the CacheTokenParser, both Component* classes have dependencies, so it does not seems easy to add the support directly on the libraries... I'll try with a fake token parser https://github.com/VincentLanglet/Twig-CS-Fixer/pull/124

**Comment by VincentLanglet** [comment]
Can you try the dev-main branch @allan-simon ?
