### ISSUE TITLE
--verbose option doesn't work as expected

### ISSUE THREAD

**Issue by phucwan91** [VincentLanglet/Twig-CS-Fixer#128]
in my case, I have some twigs file which have redundant spaces between twig filters (ex: ` 'Hello'   |   trans`), but when running `vendor/bin/twig-cs-fixer lint --fix --verbose` it just shows like this

![Screenshot from 2023-07-28 12-33-07](https://github.com/VincentLanglet/Twig-CS-Fixer/assets/38489532/ea883159-7da5-4b08-9917-10997b81cb98)

#### imo, it should show a list of fixed files so we can keep track what changed files after running the command

**Comment by VincentLanglet** [comment]
Hi can you try locally the branch https://github.com/VincentLanglet/Twig-CS-Fixer/pull/129 and tell me if it's ok for you

**Comment by phucwan91** [comment]
> Hi can you try locally the branch #129 and tell me if it's ok for you

hey, it works merci !
![Screenshot from 2023-07-28 15-26-40](https://github.com/VincentLanglet/Twig-CS-Fixer/assets/38489532/4a5b36ae-23de-453f-bde0-3a76557d01dd)

**Comment by VincentLanglet** [comment]
Released in 1.3.0

> however should it count up in the `notices` or `warnings` ?

It count every modification done to a file.
