### ISSUE TITLE
Option to exclude Symfony tokens

### ISSUE THREAD

**Issue by MauricioFauth** [VincentLanglet/Twig-CS-Fixer#133]
I didn't find a way to disable Symfony specific tokens that are included in `symfony/twig-bridge`.

If only `twig/twig` package is used and an extension is added that register a tag with the same name, but different syntax, it will cause errors. In my case, I have a `trans` tag with a different syntax than the one from `symfony/twig-bridge`.

**Comment by VincentLanglet** [comment]
Hi, does https://github.com/VincentLanglet/Twig-CS-Fixer/pull/134 solve your issue ?

Some configuration/option could indeed help for your situation, but at first this tool shouldn't install and rely on `symfony/twig-bridge` if you don't use it so I made the dependency optional.

**Comment by VincentLanglet** [comment]
1.4.0 is released
