### ISSUE TITLE
[RFC] new fixer: include function over the include tag

### ISSUE THREAD

**Issue by 94noni** [VincentLanglet/Twig-CS-Fixer#140]
Hello, a big fan of this fixer and I just saw [this PR ](https://github.com/symfony/symfony/pull/52126), what do you think of this and can it be handled via this tool?

thank you

**Comment by VincentLanglet** [comment]
Hi, it is technically doable to change:
```
{% include '@WebProfiler/Profiler/table.html.twig' with { data: collector.applicationInputs, labels: ['Input', 'Value'], maxDepth: 2 } only %}
```
to
```
{{ include('@WebProfiler/Profiler/table.html.twig', { data: collector.applicationInputs, labels: ['Input', 'Value'], maxDepth: 2 }, with_context=false) }}
```

```
{% include
```
is considered as a `BLOCK_TAG_TYPE` token with the `include` value.
if you listen those token, you can
- replace it by a `{{ include(` token
- look for the `%}` token
- if there is only, replace `only %}` by `, with_context=false) }}`
- if there is not only, replace `%}` by `) }}`

Feel free to implement this custom fixer.

**Comment by VincentLanglet** [comment]
Solved by https://github.com/VincentLanglet/Twig-CS-Fixer/pull/176
