### ISSUE TITLE
Custom reporters and output formats for errors

### ISSUE THREAD

**Issue by j-barnes** [VincentLanglet/Twig-CS-Fixer#147]
### Rule(s) related to or rule(s) missing
Awesome project, would be great to have some type of ``--reporter checkstyle`` for output so we can integrate this into our pipeline.  That way we can use annotations on pull requests to mark what needs to be fixed.

### Expected behavior
Implementing custom reports like twigcs
```
twigcs /path/to/views --reporter console
twigcs /path/to/views --reporter checkstyle
twigcs /path/to/views --reporter junit
twigcs /path/to/views --reporter emacs
twigcs /path/to/views --reporter json
twigcs /path/to/views --reporter csv
twigcs /path/to/views --reporter githubAction
twigcs /path/to/views --reporter gitlab
```

### Actual behavior
Currently do not have an option for the output format for errors.

**Comment by VincentLanglet** [comment]
Hi ! Thanks for the feedback and the suggestions.

I'm trying something with https://github.com/VincentLanglet/Twig-CS-Fixer/pull/148 WDYT about it ?

Also would you like to contribute by providing a reporter ? Like the github action one or the one you needed ?

**Comment by VincentLanglet** [comment]
Closed with https://github.com/VincentLanglet/Twig-CS-Fixer/pull/148 and https://github.com/VincentLanglet/Twig-CS-Fixer/pull/152
