### ISSUE TITLE
Unknown 'trans_default_domain' tag

### ISSUE THREAD

**Issue by mdeherder** [VincentLanglet/Twig-CS-Fixer#161]
In `Symfony 7.0`, `PHP 8.3`, `Twig 3.8.0` and `twig-cs-fixer 2.0.0`, I suddenly get an error for the `trans_default_domain` tag.

```
  FATAL   1    | {% extends '@EasyAdmin/page/content.html.twig' %}
          2    | {% trans_default_domain 'EasyBundle' %}
          >>   | File is invalid: Unknown "trans_default_domain" tag.
          3    | {% block page_title 'Welcome'|trans %}
```
or
```
  FATAL   1    | {% apply inky_to_html|inline_css(encore_entry_css_source('mail')) %}
          2    | {% trans_default_domain 'security' %}
          >>   | File is invalid: Unexpected "trans_default_domain" tag (expecting closing tag for the "apply" tag defined near line 2).
          3    | <container>
```

**Comment by VincentLanglet** [comment]
Hi, you didn't have the issue with the 1.6 version ?

**Comment by mdeherder** [comment]
Yes, having had the error in version 1.60 I upgraded to 2.0.0 believing it would be corrected.

**Comment by VincentLanglet** [comment]
> Yes,
> 
> ```
> composer show symfony/twig*
> symfony/twig-bridge v7.0.0 Provides integration for Twig with various Symfony components
> symfony/twig-bundle v7.0.0 Provides a tight integration of Twig into the Symfony full-stack framework
> ```

In the same composer than the one you installed the twig-cs-fixer tool ?

If you have this class in your vendor,
https://github.com/symfony/twig-bridge/blob/7.0/TokenParser/TransDefaultDomainTokenParser.php#L24
it's supposed to be loaded.

**Comment by mdeherder** [comment]
> In the same composer than the one you installed the twig-cs-fixer tool ?

No !
After installation of symfony/twig-bridge in the global composer, the problem is solved.

Thanks,
