### ISSUE TITLE
Example in the docs 

### ISSUE THREAD

**Issue by pieterocp** [VincentLanglet/Twig-CS-Fixer#182]
### Rule(s) related to or rule(s) missing

Not a rule, just the example in the `.docs/configuration.md` looks to be a bit misleading.

### Expected behavior

Copy and pasting the config snippet works without any issues.

### Actual behavior

Get back an `Error: TwigCsFixer\Ruleset\Ruleset::addRule(): Argument #1 ($rule) must be of type TwigCsFixer\Rules\RuleInterface, string given, called in /srv/.twig-cs-fixer.dist.php on line 5`

Looks like amending the snippet from 
`$ruleset->addRule(\TwigCsFixer\Rules\Whitespace\EmptyLinesRule::class);`
to 
`$ruleset->addRule(new \TwigCsFixer\Rules\Whitespace\EmptyLinesRule());`
looks like it works as expected. 

N.b. first time using this, I might have missed something obvious.

**Comment by VincentLanglet** [comment]
Thanks for reporting my mistake, it's fixed now :)
