### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Daviid-P** [VincentLanglet/Twig-CS-Fixer#190]
When I run 

`./vendor/bin/twig-cs-fixer lint --verbose /templates/components/datatable.twig`

I got the message of "using cache", and nothing else, like it hangs, I deleted the cache file just in case and now I get no output.

Is there any way to force any output to see if I'm suppressing any errors?

**Comment by VincentLanglet** [comment]
Hi,

When I run the command I get an output
<img width="965" alt="image" src="https://github.com/VincentLanglet/Twig-CS-Fixer/assets/9052536/b3469367-ad18-4b41-b1a0-62974d5bec77">

Which version do you use ?
Do you have a `.twig-cs-fixer.dist.php` config ?

**Comment by Daviid-P** [comment]
I installed php8 just to install latest twig-cs-fixer and it works fine, not sure what problems I could come across using php8 just for linting, I assume this is just concerned with twig style and guidelines and I don't use PHP code inside my templates.

**Comment by VincentLanglet** [comment]
> I installed php8 just to install latest twig-cs-fixer and it works fine, not sure what problems I could come across using php8 just for linting, I assume this is just concerned with twig style and guidelines and I don't use PHP code inside my templates.

- PHP 7.4/8 are EOL for at least one year.
- It's easier to write tool with up to date php version
- By using php > 8 you also able to get the latest twig-cs-fixer versions, the 0.6.1 was released in 2022

Great if works with latest versions
