### ISSUE TITLE
Error: Infinite loop

### ISSUE THREAD

**Issue by seb-jean** [VincentLanglet/Twig-CS-Fixer#197]
Hi :),

I have a bellow error:
`Error: Infinite loop`

Why do I get this error displayed?
Thanks :)

**Comment by VincentLanglet** [comment]
Hi, is it thrown by this line ?
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/5f364b9dcc64ea0743698834bd2cdb64e15d08bb/src/Token/Tokenizer.php#L149

This shouldn't occur. I will need your file (or a small reproducer if you can have) to reproduce the error.
I assume that I may still handle badly some of your end of line character (or something similar with windows ?)

Do you use the latest version ?

**Comment by seb-jean** [comment]
I deleted the contents of the problematic files, ran the command line and put the contents back. It works.

**Comment by VincentLanglet** [comment]
> I deleted the contents of the problematic files, ran the command line and put the contents back. It works.

Too bad, I was curious how it was possible to reach this logic exception.

**Comment by VincentLanglet** [comment]
If you can reproduce it again, maybe the error message will be better with https://github.com/VincentLanglet/Twig-CS-Fixer/pull/200 merged
