### ISSUE TITLE
[RFC] rule `VariableNameRule` allowing variable prefix `_`

### ISSUE THREAD

**Issue by 94noni** [VincentLanglet/Twig-CS-Fixer#219]
### Rule(s) related to or rule(s) missing

v2.8 VariableNameRule

### Expected behavior

`{% set _user_email = user.email %}` dont produce an error with `snake_case` config of `VariableNameRule`

### Actual behavior

error, as `_` is not handled now

---

Hello 👋🏻 

in our quite big codebase, we are used to an "internal twig standard" where variable passed form controller are `snake_case` and the one defined inside a twig template are `_snake_case`

so may I propose an RFC: can we imagine a configuration allowing a prefix for var naming?

This RFC can extends to:

- `FileNameRule` (we name some partial views like `/_info.html.twig`)
- `DirectoryNameRule` (we name some folder containing only partial views like `_blocks/`)

**Comment by VincentLanglet** [comment]
> This RFC can extends to:
> 
> * `FileNameRule` (we name some partial views like `/_info.html.twig`)
> * `DirectoryNameRule` (we name some folder containing only partial views like `_blocks/`)

There is already an optional prefix for those rule.

I'm ok adding one to VariableNameRule.
https://github.com/VincentLanglet/Twig-CS-Fixer/pull/221

**Comment by 94noni** [comment]
fantastic thank you,
I did not checked deeper the other classes so thx for pointing out
