### ISSUE TITLE
[DX] Aliases "check" & "fix"

### ISSUE THREAD

**Issue by smnandre** [VincentLanglet/Twig-CS-Fixer#223]
i'd like to have two aliases: `check` & `fix `, so i started to see how that could be done.

This seems to work perfectly by adding thoses aliases in the entry point, and two lines in the command 

```php
// bin/twig-cs-fixer

// ...

$command = new TwigCsFixerCommand();
$command->setAliases(['fix', 'check']);

$application = new Application();
```

```php
// TwigCsFixerCommand.php


    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        if ('check' === $input->getArgument('command')) {
            $input->setOption('fix', false);
        } elseif ('fix' === $input->getArgument('command')) {
            $input->setOption('fix', true);
        }
```

Would you be open to that ? If yes do you think there is a better way to implement it ?

**Comment by VincentLanglet** [comment]
> Would you be open to that ?

Yes, but I would say it requires some thought about what should be the right aliases.

> If yes do you think there is a better way to implement it ?

I think `setAliases` can be called directly in `TwigCsFixerCommand::configure`.

My only concern is "What if someone use `check --fix` or `fix --fix`. There is multiple solution
- `check --fix` behave like `lint --fix` and `fix --fix` like `fix`
- `--fix` option fails with `fix` and `check`.

Another way to implement such alias would be to extends the command like it's done in the `PHP-Cs-Fixer` check command: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Console/Command/CheckCommand.php

Or maybe we add a constructor
```
public function __construct(
    private string $name = self::DEFAULT_NAME,
    private string $description = self::DEFAULT_DESCRIPTION, 
    private ?bool $fix
) {
} 
```
with 
```
protected function configure(): void
    {
        $this
            ->setName(self::DEFAULT_NAME')
            ->setDescription(self::DEFAULT_DESCRIPTION)
            ->setDefinition(is_bool($fix) ? $inputOptionsWithoutFix : $inputOptions);
```
and 
```
true === $this->fix || $input->hasOption('fix') && $input->getOption('fix') ? new Fixer($tokenizer) : null,
```

so it could be declared this way:
```
$command = new TwigCsFixerCommand();
$aliases = [
    new TwigCsFixerCommand('check', 'TODO', false),
    new TwigCsFixerCommand('fix', 'TODO', true),
];

$application = new Application();
$application->add($command);
foreach ($aliases as $alias) {
    $application->add($command);
}
$application->setDefaultCommand($command->getName());
$application->run();
```

I really dunno what is the best strategy...

**Comment by smnandre** [comment]
> My only concern is "What if someone use `check --fix` or `fix --fix`. There is multiple solution

To me, `fix --fix ` has no point, so i have no opinion on throwing or ignoring

And in the end, _in my mind_,  `check --fix` should be tolerated.

--

Php-Cs-Fixer has a "--dry-run" option for the "fix" command, and a "check" alias for it


```shell
# Accepted, and works as expected
phpcs fix  --dry-run
```

```shell
# Accepted, and works as expected (so as "fix --dry-run)
phpcs check
```

```shell
# Error
phpcs check --dry-run
    The "--dry-run" option does not exist.
```

--

So that'd give here: 
* define the check alias in the existing command (as it's 100% an alias)
* create a fix command that extends the current one and sets the "--fix" option) 


WDYT ?

**Comment by VincentLanglet** [comment]
> So that'd give here:
> 
> * define the check alias in the existing command (as it's 100% an alias)
> * create a fix command that extends the current one and sets the "--fix" option)
> 
> WDYT ?

I agree, especially because aliases and another command are displayed differently 
<img width="566" alt="image" src="https://github.com/VincentLanglet/Twig-CS-Fixer/assets/9052536/3caff76f-0d1b-4ed6-b0ac-4f041e9ec516">

But I just remembered one reason which could not play in favor of a `fix` alias/command: all the rules are not automatically fixable. For instance, I don't fix automatically variable name since it could break the application https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/src/Rules/Variable/VariableNameRule.php#L80

Wouldn't be weird to have a `fix` command which doesn't fix every time and still output errors you have to fix manually ?

**Comment by smnandre** [comment]
> Wouldn't be weird to have a fix command which doesn't fix every time and still output errors you have to fix manually ?

That does not change really more than the current situation (in my mind) .. If it's documented as today "Automatically **fix all the fixable violations**"

The question is more "what status code when all fixable violations have been fixed" i guess ?

**Comment by VincentLanglet** [comment]
I think I'll follow your strategy, it seems to be the simplest @smnandre 
https://github.com/VincentLanglet/Twig-CS-Fixer/pull/240
