### ISSUE TITLE
include syntax

### ISSUE THREAD

**Issue by rafipiccolo** [VincentLanglet/Twig-CS-Fixer#228]
### Rule(s) related to or rule(s) missing
There seem to be a recent change (version 2.9.0) with the way you format includes.
But this new way, valid in twig v3, makes my code fail since i use twigjs and it does not support it
can i disable this particular rule ?

### Expected behavior

```
{% include('template.html') with vars %}
```

### Actual behavior

```
{{ include('template.html', vars) }}
```

**Comment by VincentLanglet** [comment]
Hi !

I dunno twigjs ; I'm curious, is there other syntaxes which are not supported ? Is it planned to be supported ?

I'll do some investigations and maybe only add the IncludeRule conditionnally or remove it of the standard by default.

Until then you can add a config and call "removeRule" in it. There is some doc about it.

**Comment by rafipiccolo** [comment]
i use twigjs on my nodejs projects and dont know any other thing that are not supported.
i filed an issue, and they likely will cover this case.

by the meantime i'll use this config :

```
<?php

$ruleset = new TwigCsFixer\Ruleset\Ruleset();

// You can start from a default standard
$ruleset->addStandard(new TwigCsFixer\Standard\TwigCsFixer());

// And then add/remove/override some rules
$ruleset->removeRule(TwigCsFixer\Rules\Function\IncludeFunctionRule::class);

$config = new TwigCsFixer\Config\Config();
$config->setRuleset($ruleset);

return $config;
```

you can close the issue if you want.
