### ISSUE TITLE
Add task for GrumPHP

### ISSUE THREAD

**Issue by antoniovj1** [VincentLanglet/Twig-CS-Fixer#229]
I'm creating this issue to document that I'm adding a new task to GrumPHP.

https://github.com/phpro/grumphp/pull/1131

Feel free to suggest improvements to this task or close the issue, @VincentLanglet.

**Comment by VincentLanglet** [comment]
Thanks, I'll take a look at the PR.

Still closing the issue since there is nothing to do on the Twig-Cs-Fixer repository side.
