### ISSUE TITLE
Option to use tabs

### ISSUE THREAD

**Issue by muuvmuuv** [VincentLanglet/Twig-CS-Fixer#232]
### Rule(s) related to or rule(s) missing

- Whitespace\IndentRule
- Whitespace\IndentStyle ← missing

### Expected behavior

Should convert spaces to tabs by indention rule.

### Actual behavior

No rule to use tabs instead of spaces.

**Comment by VincentLanglet** [comment]
Hi @muuvmuuv,

> Should convert spaces to tabs by indention rule.

If you have the following code
```
Tab - 5 spaces - Foo - 5 spaces - Bar
```
Do you expect:
```
Tab - Tab - 1 space - Foo - 5 spaces - Bar
```
?

And what do you mean by
> Whitespace\IndentStyle ← missing

**Comment by muuvmuuv** [comment]
If I say my setting is one tab indention and one tab equals two spaces it would just be
```
Tab - Foo - 5 Spaces - Bar
```

In the GitHub issue template it says "...rule(s) missing", so I expected that means I need to provide an example of a missing rule?

**Comment by VincentLanglet** [comment]
> In the GitHub issue template it says "...rule(s) missing", so I expected that means I need to provide an example of a missing rule?

I think it will be more an option to add to `Whitespace\IndentRule`

> If I say my setting is one tab indention and one tab equals two spaces it would just be
> 
> ```
> Tab - Foo - 5 Spaces - Bar
> ```

I kinda disagree here. Code ca be indented with
- 0 tab
- 1 tab
- 2 tabs
- etc

for instance
```
<div class="div1">
	<div class="div2>
		<p> Text </p>
	</div>
</div>
```

I agree on the fact I need a spaceRatio between tabs and space (you use one tab for two spaces, I generally see one tab for 4 spaces). But I can only replace x spaces by one tab, without removing tabs or extra spaces. So the rule (with a 4 space ratio) will replace
- 8 spaces by 2 tabs
- 10 spaces by 2 tabs and 2 spaces
- 1 tab and 4 spaces by 2 tabs
- 1 tab and 6 spaces by 2 tabs and 2 spaces

This is the best I can do IMHO.

**Comment by muuvmuuv** [comment]
Oh, sorry I misunderstood you with the "5 spaces", yes you are right, some ratio is needed in order to replace them correctly.

If tabs are used, I would expect overflowing spaces to be removed if they aren't in the ratio range, otherwise the option wouldn't make sense for a fixed indention.

**Comment by VincentLanglet** [comment]
> If tabs are used, I would expect overflowing spaces to be removed if they aren't in the ratio range, otherwise the option wouldn't make sense for a fixed indention.

I let this to another Rule in creation which would be `IndentLengthRule` checking that indentation is a multiple of space ratio or tabs.

**Comment by muuvmuuv** [comment]
Here a playground with your example: https://biomejs.dev/playground/?lintRules=all&code=CgBjAGwAYQBzAHMAIABUAGUAcwB0ACAAewAKACAAIAAgACAAIAAgACAAIAB2ADEAIAA9ACAAIgAiACAALwAvACAAOAAgAHMAcABhAGMAZQBzACAAYgB5ACAAMgAgAHQAYQBiAHMACgAgACAAIAAgACAAIAAgACAAIAAgAHYAMgAgAD0AIAAiACIAIAAvAC8AIAAxADAAIABzAHAAYQBjAGUAcwAgAGIAeQAgADIAIAB0AGEAYgBzACAAYQBuAGQAIAAyACAAcwBwAGEAYwBlAHMACgAgACAAIAAgACAAIAB2ADMAIAA9ACAAIgAiACAALwAvACAAMQAgAHQAYQBiACAAYQBuAGQAIAA0ACAAcwBwAGEAYwBlAHMAIABiAHkAIAAyACAAdABhAGIAcwAKACAAIAAgACAAIAAgACAAIAB2ADQAIAA9ACAAIgAiACAALwAvACAAMQAgAHQAYQBiACAAYQBuAGQAIAA2ACAAcwBwAGEAYwBlAHMAIABiAHkAIAAyACAAdABhAGIAcwAgAGEAbgBkACAAMgAgAHMAcABhAGMAZQBzACAAIAAKAH0ACgAKAG4AZQB3ACAAVABlAHMAdAAoACkACgA%3D

**Comment by rrenteria-dev** [comment]
+1

**Comment by VincentLanglet** [comment]
WIP https://github.com/VincentLanglet/Twig-CS-Fixer/pull/236 ; any feedback is welcome

**Comment by rrenteria-dev** [comment]
> WIP #236 ; any feedback is welcome

Amazing! Will test it out! 
Thank you for your hard work, this linter is amazing. 

Not trying to hijack the subject, but by any chance can you give me a pointer about how to use your tool inside vscode? php-cs-fixer does a terrible job as a formatter.

**Comment by VincentLanglet** [comment]
> Not trying to hijack the subject, but by any chance can you give me a pointer about how to use your tool inside vscode? php-cs-fixer does a terrible job as a twig* formatter.

There is no native integration of twig-cs-fixer inside phpstorm/vscode so far.
I assume someone need to implement an integration ; I won't be this guy.
