### ISSUE TITLE
Trailing comma rule

### ISSUE THREAD

**Issue by yoriiis** [VincentLanglet/Twig-CS-Fixer#238]
Hello,

First of all, thank you for this project, it's very useful, we use it on many projects in our company!

### Rule(s) related to or rule(s) missing

Add a rule for the trailing comma character.

Since Twig has allowed the trailing comma (see https://github.com/twigphp/Twig/pull/3363), perhaps the default should be to keep it, but allow it to be deleted. What do you think?

### Expected behavior

```twig
{% set data = {
    title: 'Custom title'
} %}
```

### Actual behavior

```twig
{% set data = {
    title: 'Custom title',
} %}
```

**Comment by VincentLanglet** [comment]
Sure, do you want to try implementing the rule ?

It could be interesting to have 
- SingleLineTrailingCommaRule: A rule removing trailing comma for single-line function call / filter argument / macro parameter / macro argument
- MultiLineTrailingCommaRule: A rule adding (or removing) trailing comma  for multi-line function call / filter argument / macro parameter / macro argument

**Comment by yoriiis** [comment]
You're fast, thanks!

In the example below, is the final comma necessary? 🤔

```twig
{{ include('template.html.twig', {
    Data,
}, false,) }}
```

Apart from that, it seems okay to me!

**Comment by yoriiis** [comment]
Another question, is there a solution for deactivating a single rule and inheriting the others with the configuration file?

As the configuration file requires you to manually specify all the rules to be included, there is a risk of deviating from the newly added rules.

For example, the rule `TrailingCommaMultiLineRule` is the only one I wish to deactivate

**Comment by VincentLanglet** [comment]
> You're fast, thanks!
> 
> In the example below, is the final comma necessary? 🤔
> 
> ```
> {{ include('template.html.twig', {
>     Data,
> }, false,) }}
> ```
> 
> Apart from that, it seems okay to me!

Thanks for the feedback. I considered that a method was multiline if the `(` and `)` were not on the same line. I changed the strategy in a new commit. Can you try again ?

> Another question, is there a solution for deactivating a single rule and inheriting the others with the configuration file?

You can add a Standard and remove a rule
see https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/docs/configuration.md

```
$ruleset = new TwigCsFixer\Ruleset\Ruleset();

// You can start from a default standard
$ruleset->addStandard(new TwigCsFixer\Standard\TwigCsFixer());

// And then add/remove/override some rules
$ruleset->removeRule(TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule::class);
$ruleset->addRule(new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule(false));

// Which is the same than
$ruleset->overrideRule(new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule(false));

$config = new TwigCsFixer\Config\Config();
$config->setRuleset($ruleset);

return $config;
```

**Comment by yoriiis** [comment]
Thanks for the configuration example.

There's still one point I don't understand: how can I check that I don't have an end comma (the opposite of the rule)? I'd like the package to trigger an error with the following code, for example

```twig
{% set data = {
    title: 'Custom title',
} %}
```

**Comment by VincentLanglet** [comment]
> There's still one point I don't understand: how can I check that I don't have an end comma (the opposite of the rule)? I'd like the package to trigger an error with the following code, for example
> 
> ```
> {% set data = {
>     title: 'Custom title',
> } %}
> ```

Did you tried `new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule(false)` as given in the example ?

It's work fine on my side, removing the comma.

**Comment by yoriiis** [comment]
Okay sorry for the misunderstanding on the example.

When the rule `TrailingCommaMultiLineRule` is enabled, it works and with the `fix` flag also.

But, when the rule `TrailingCommaMultiLineRule` is disabled

```php
$ruleset->addRule(new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule(false));
```

There are the following errors:

- The linter reports that there should be a comma at the end when there shouldn't be. `Error: Multi-line arrays, objects and parameters lists should have trailing comma`
- No fix is made and there is a fatal error: `Fatal: Unable to fix file: Too many iterations while trying to fix file. Error: Multi-line arrays, objects and parameters lists should have trailing comma`

This example trigger the error:

```twig
{% block meta %}
    {{ include('@metas.html.twig', {
        Metadata,
        ArticleContent
    }) }}
{% endblock %}
```

**Comment by VincentLanglet** [comment]
> But, when the rule `TrailingCommaMultiLineRule` is disabled
> 
> ```
> $ruleset->addRule(new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule(false));
> ```

I assume you also have
```
$ruleset->addStandard(new TwigCsFixer\Standard\TwigCsFixer());
```

Then you misunderstood how the conf works.

A way to totally disable a rule is 
```
->removeRule(TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule::class);
```

Because
```
->addRule(new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule(false));
```
doesn't disable the rule, it enable the rule but remove the trailing comma.

Also, since the rule is added by the standard with `true` you ended up with the rule added two times, one time with true and one time with false ; giving the infinite loop.

The right way to override a rule config is 
```
->overrideRule(new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule(false));
```

**Comment by yoriiis** [comment]
Thanks for the clarification @VincentLanglet, it works!

**Comment by yoriiis** [comment]
@VincentLanglet do you think the `TrailingCommaMultiLineRule` rule has the right default value? Twig has added this option, but should it become standard?

For example, the default `TrailingCommaSingleLineRule` ensures that there is no trailing comma.

**Comment by VincentLanglet** [comment]
> @VincentLanglet do you think the `TrailingCommaMultiLineRule` rule has the right default value? Twig has added this option, but should it become standard?
> 
> For example, the default `TrailingCommaSingleLineRule` ensures that there is no trailing comma.

Yes, I'm sure, for at least 2 reasons.

One. The TwigCsFixer is and will still be an opinionated standard (kinda personal).

"Official" standard are the Symfony one and the Twig one. And there nothing about trailing comma in there.

And two, if you look at similar rule in PHP-Cs-Fixer, you'll see
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/no_trailing_comma_in_singleline.rst => Similar to TrailingCommaSingleLineRule
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/control_structure/trailing_comma_in_multiline.rst => Similar to TrailingCommaMultiLineRule (And there is no config in it)

You can find similar thing for js linter and many others.

Some article explain why you should prefer trailing comma in multi line statements.
https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8
