### ISSUE TITLE
[RFC] New rule to inline block definitions with a single expression

### ISSUE THREAD

**Issue by yguedidi** [VincentLanglet/Twig-CS-Fixer#244]
Add a new rule to move for exemple from:

```twig
{% block title %}
    {{ 'page.title'|trans }}
{% endblock %}
```

to

```twig
{% block title 'page.title'|trans %}
```

Any expression in a single `{{ ... }}` inside the block should be safe to be changed.

**Comment by VincentLanglet** [comment]
Hi, this rule seems really opinionated and I'm unsure about the popularity.

But I can help you implementing it. Notice rules can either be implemented in this repository or you can implement them directly in your projet and adding them to your config.

```
{% block title %}
{{ 'page.title'|trans }}
{% endblock %}
```
is parsed as
- TOKEN::BLOCK_START_TYPE
- TOKEN::WHITESPACE_TYPE
- TOKEN::BLOCK_NAME_TYPE
- TOKEN::WHITESPACE_TYPE
- TOKEN::NAME
- TOKEN::WHITESPACE_TYPE
- TOKEN::BLOCK_END_TYPE
- TOKEN::EOL_TYPE
- TOKEN::VAR_START_TYPE
- and so on

You may look for every BLOCK_NAME_TYPE, if it's a `block` then you look for BLOCK_END_TYPE,
Then you can find for the first non empty token, if it's a VAR_START_TYPE, you look for `VAR_END_TYPE` then you find for the next non empty token and if it's the `{% endblock %}` block, you can do the text modification you want.

**Comment by yguedidi** [comment]
Hi! Thank you for the guidance!
Indeed I understand it is quite opinionated 😅
Especially that it can get even more complex if we expect a way or the other depending on the "complexity" of the expression..
May give it a try one day at work, if I have the opportunity.
Meanwhile I'll close this and thanks again.
