### ISSUE TITLE
Remove excess spacing before multiline block `%}`

### ISSUE THREAD

**Issue by ruudk** [VincentLanglet/Twig-CS-Fixer#245]
### Rule(s) related to or rule(s) missing

Using the standard TwigCsFixer rules I notice something odd.

### Actual behavior

```twig
{% trans 'my.key' with {
    faqUrl: 'http://faq',
    contactUrl: 'http://contact',
    }

%}
```

### Expected behavior

```twig
{% trans 'my.key' with {
    faqUrl: 'http://faq',
    contactUrl: 'http://contact',
    } %}
```

Why isn't the excess newline and spacing not removed?

**Comment by ruudk** [comment]
I agree that this might be a preference that shouldn't be enabled by default. 

So I'm all ears for introducing a new option that defaults to the current behavior.

**Comment by VincentLanglet** [comment]
> So I'm all ears for introducing a new option that defaults to the current behavior.

I'll be at least one week off so won't be able to help on this soon.

But if you want to try
- AbstractSpacingRule will implements ConfigurableRuleInterface
- AbstractSpacingRule will have a construct with `skipNewLine = true`
- The `getConfiguration` need to be implemented
- `checkSpaceAfter` and `checkSpaceBefore` need to be updated to handle the `skipNewline` option

```
// Ignore new line
$next = $this->findNext(Token::INDENT_TOKENS, $tokens, $tokenPosition + 1, true);
```
will certainly be `Token::INDENT_TOKENS + Token::EOL_TOKENS` when we don't skip EOL. But then maybe the count of whitespace and message will need to be modified (I dunno).

And test will be necessary.

**Comment by ruudk** [comment]
I tried something in https://github.com/VincentLanglet/Twig-CS-Fixer/pull/247 but I couldn't get it to work.
