### ISSUE TITLE
Security policy questions

### ISSUE THREAD

**Issue by feuerwagen** [VincentLanglet/Twig-CS-Fixer#255]
The Drupal project is considering adding this library as one of our development dependencies and so we're performing a standard security review. The issue in our issue tracker is https://www.drupal.org/project/drupal/issues/3284817

There is no security policy listed at https://github.com/VincentLanglet/Twig-CS-Fixer/security/policy so I was wondering if you have an official policy on any security issues discovered in this module?

Other useful information would include: 
- Supported versions
- Semver support (which seems to be the case, looking at the releases so far)

Thanks for your time!

**Comment by VincentLanglet** [comment]
Hi, do you have a security file example I need to add ? Ill add one.

For your questions:
- I only support the latest major
- I try to respect semver

**Comment by feuerwagen** [comment]
@VincentLanglet Thx for the swift response. I posted a PR with a minimal suggestion.
