### ISSUE TITLE
code break with comma added on multiline if statements with parentheses

### ISSUE THREAD

**Issue by rafipiccolo** [VincentLanglet/Twig-CS-Fixer#256]
### Rule(s) related to or rule(s) missing

dunno

### Expected behavior
```
{% if property.rentsellType == 'property.rentsellType.rent' and (
    property.entretien or
    property.chauffage or
    property.entretienJardin
    )
%}
{% endif %}
```

### Actual behavior

it adds a comma on the last line, after "entretienJardin"

```
{% if property.rentsellType == 'property.rentsellType.rent' and (
    property.entretien or
    property.chauffage or
    property.entretienJardin,
    )
%}
{% endif %}
```

**Comment by VincentLanglet** [comment]
Hi, can you open a PR to remove the Rule from the TwigCsFixer standard as it's a buggy rule so far ?

I wont have a computer before this night

**Comment by VincentLanglet** [comment]
I'm working on a 3.0 release with BC-break needed in order to fix the rule.
If you @rafipiccolo (or @thislg) want to try it, it would be great. Both of your bug should be fixed.
