### ISSUE TITLE
Bug:  Disabling rules for file, line, or next line not working

### ISSUE THREAD

**Issue by vd-lhridley** [VincentLanglet/Twig-CS-Fixer#296]
### Issue

{# twig-cs-fixer-disable #} => Disable every rule for the whole file
{# twig-cs-fixer-disable-line #} => Disable every rule for the current line
{# twig-cs-fixer-disable-next-line #} => Disable every rule for the next line

These tags don't do anything when placed at the top of a file, above a line to skip, or on a line to skip

**Comment by VincentLanglet** [comment]
Hi @vd-lhridley,

I'm surprised about this since:
- I have multiple unit tests
- I'm using this tags

Which version do you use ?
Do you have an example of code where you still get the error ?

**Comment by vd-lhridley** [comment]
Looks like we are using version 2.11. 

Attached is a file that fails with the following error:

`File is invalid: A message inside a trans tag must be a simple text. `

**Comment by VincentLanglet** [comment]
> File is invalid: A message inside a trans tag must be a simple text.

Those message were not able to be disable.

But this "static analysis" was removed in the 3.x branch so I recommend you to bump the linter version and it will solve your issue.

**Comment by lhridley** [comment]
No can do, the project we're attempting to use this on has several packages dependent upon twig/twig 3.8.0.  The 3.x version of this package requires a minimum of twig/twig 3.10 or higher, as does versions higher than 2.11.0.  Package won't install, which is why we had version 2.11 installed.

**Comment by lhridley** [comment]
ok, force the update to 3.0.0 with "3.0.0 as 2.11.0", which was needed because of other packages dependent on twig/twig version 3.8.0.  This library requires a minimum twig/twig version of 3.10.0.

**Comment by VincentLanglet** [comment]
I dont have a computer this week end but cant you bump the twig version to correctly using the latest version without composer hack ? Bumping minor version should be allowed...

The "File is invalid" error seems weird since in the "real" 3.0 version I dont think I returns such error anymore.

Do you have a custom twig cs fixer config ?

**Comment by VincentLanglet** [comment]
> The "File is invalid" error seems weird since in the "real" 3.0 version I dont think I returns such error anymore.
> 
> Do you have a custom twig cs fixer config ?

I double checked and unless you're using Node based rules (which are NOT enabled by default), there is no error `File is invalid` in 3.x version, so you may not have correctly installed the latest version.

**Comment by smnandre** [comment]
@lhridley 

```
>>   | File is invalid: A message inside a trans tag must be a simple text.   
```

I believe this is a Twig compilation error, not a Twig-CS-Fixer rule one.  

You seem to have this code in your template.

```twig
{% trans %}Submitted by {{ author_name }} on {{ date }}{% endtrans %}
```

But the trans tag content **must be static** (no variable, echo, etc..)

From the [documentation ](https://symfony.com/doc/current/translation.html#using-twig-tags):

>  Symfony provides a specialized Twig tag trans to help with message translation of **static blocks of text**:



I think there is nothing here TwigCSFixer can do: you have to fix your template, so it passes at least compilation step.

**Comment by VincentLanglet** [comment]
> @lhridley
> 
> ```
> >>   | File is invalid: A message inside a trans tag must be a simple text.   
> ```
> 
> I believe this is a Twig compilation error, not a Twig-CS-Fixer rule one.

Definitely since this compilation was removed from Twig-CS-Fixer in 3.0.

**Comment by vd-lhridley** [comment]
Instead of focusing on the syntax of the file that is failing linting, can we focus on the fact that the Ignore rules are not working?  None of this discussion is helping the fact that the Ignore rules don't actually do anything.

I am not the only person having this issue:  https://www.drupal.org/project/drupal/issues/3284817#comment-15729173

This is potentially a blocker for adoption by the Drupal community.

**Comment by VincentLanglet** [comment]
> None of this discussion is helping the fact that the Ignore rules don't actually do anything, including version 3.0 of this project.

As explained, I don't think you're using the version 3.0.
- `File is invalid` errors were removed from the 3.0 version.

So focus on using the 3.0 version.

And if you're stuck because of another library which is stuck with twig 3.8
- You should report an issue for this lib that twig 3.8 is not supported anymore and they should move forward
- You can still try to use the PHAR of Twig-CS-Fixer or install this in a specific bin dir

> that the Ignore rules don't actually do anything

Ignoring a rule works on a RULE. You're trying to ignore a parsing error. And parsing a file was needed for 2.x versions.

**Comment by VincentLanglet** [comment]
@vd-lhridley You should be able to install the 3.0.2 version.
