### ISSUE TITLE
Rule Ideas: A11y Rules

### ISSUE THREAD

**Issue by snoweuph** [VincentLanglet/Twig-CS-Fixer#298]
### Rule(s) related to or rule(s) missing
A11y (Accesibilty) is getting a bigger thing, and has some [new Laws in Germany](https://bfsg-gesetz.de/) following the [EU 2019/882](https://eur-lex.europa.eu/eli/dir/2019/882/oj?locale=de) that have to be followed, or big Lawsuits can happen.
It would be cool to have some rules that could find a11y related stuff in your twig templates and possibly even fix some of them automatically

The A11y Spec: https://www.a11yproject.com/checklist/
There was a WIP RuleSet for the old FriendsOfTwig CS Fixer: https://github.com/NielsdeBlaauw/twigcs-a11y

### Expected behavior

Twig cs fixer can tell me about stuff that I should fix related to accessibility (like aria labels)

### Actual behavior
It cant yet :(

**Comment by VincentLanglet** [comment]
Hi, having perfectly implemented rules would be hard because of how twig works and this is certainly why there is almost no rule in the [NielsdeBlaauw/twigcs-a11y](https://github.com/NielsdeBlaauw/twigcs-a11y) repository.

You can write things like
```
{% if image %}
<img
{% else %}
<div
{%endif
class="..."
{% if foo %}
foo=bar
{% endif
>
```
and it's kinda complicated to understand if the img has all the required attributes.

Also this lib doesn't parse HTML, only twig.
`<img src="img_girl.jpg" alt="Girl in a jacket" width="500" height="600">` is considered as
- Text `<img`
- Whitespace
- Text `src="img_girl.jpg"`
- Whitespace
- Text `alt="Girl in a jacket"`
- Whitespace
- Text `width="500"`
- Whitespace
- Text `height="600">`

which doesn't help writing such rules.

**Comment by snoweuph** [comment]
I don't expect a perfect implementation, but Developers are just humans.
Having automated pipelines running first, and then taking time to check stuff, after they are saying that everything is right, can highly simplify such work, and how often accessibility needs to be tested.

Looking at the Technical Case, I would also say, that an extra experimental repository for experimental extensions like this would make sense.

Alone having it checking for the possibility of there being aria-tags and labels, would already be an improvement, because the fixer can be used locally for linting, and in the CI.

I dont exspect any tool to completely replace a full WAST test, but it means caching problems earlier.

**Comment by smnandre** [comment]
I'd be interested to see two or three concrete examples.. with the twig code that would be marked "invalid" and the reason.

I fear this can only cover a very limited subset of use case, as an important part of aria attributes are runtime based.

**Comment by snoweuph** [comment]
## Here are some:

**Invalid:** Image doesn't have an `alt` text
```twig
<img />
```

**Valid:**
```twig
<img alt="Cake"/>
```
----

**Invalid:** There should always be an `alt` Tag
```twig
<img src="" {% if condition%} alt="cake" {% endif %}>
```

**Valid:** We don't 100% know that the `alt_text` var is set, but at least we know that there is an alt tag on that image. Verifying exact content shouldn't be the job of the Fixer
```twig
<img  alt="{{ alt_text }}">
```
----

**Invalid:** Headers should be in consecutive order. The Start of that order (there should always be an h1) isn't important, though, because it can't be checked for by twig cs fixer.
```twig
<h2>A<h2>
<h4>B</h4>
<h5>C</h5>
```

**Valid:**
```twig
<h2>A<h2>
<h3>B</h3>
<h4>C</h4>
```
---

**Invalid:** HTML Tags should have a language defined for screen readers
```twig
<html>
```

**Valid:**
```twig
<html lang="en">
```
---

**Invalid:** `a` should use `href` instead of `onclick`
```twig
<a onclick="redirect()">
```

**Valid:**
```twig
<a href="https://github.com/VincentLanglet/Twig-CS-Fixer/issues/298">
```
----

**Invalid:** Videos shouldn't have autoplay, when not `muted`
```twig
<video autoplay>
```
```twig
<video autoplay {% if should_mute%}muted{% fi %}>
```

**Valid:**
```twig
<video autoplay muted>
```
```twig
<video  {% if should_autplay%}autoplay muted{% fi %}>
```

**Comment by smnandre** [comment]
I really think these rules could only (and more easily) checked by looking at the _generated_ HTML.

I fear every exemple you are giving would be silenced with a simple "include" or any Twig tag/filter/function ... so the end result would  only give a very partial vision of the problems.

And i'm not talking about the difficulty to parse HTML mixed with Twig tags ..  🤷‍♂️ 

> Having automated pipelines running first, and then taking time to check stuff, after they are saying that everything is right, can highly simplify such work, its complexity and the time needed.

Some basic functionnal tests could be perfect place for this!

If you work with Symfony, you can implement this kind of checks with the DomCrawler provided by the WebTestCase client: https://symfony.com/doc/current/testing.html#testing-the-response-assertions

**Comment by snoweuph** [comment]
Guess, I will just have to pull full E2E in all projects, but I get the Points.
the DomCrawler is just a worse Version of real E2E, and out of my experince buggy.

**Comment by smnandre** [comment]
>  I will just have to pull full E2E in all projects

@snoweuph I don't think full E2E are needed, as JS should not be required to comply with Ally. 

So a simple WebTestCase with no real DOM execution will be enough (and a lot quicker to execute).

You can look at [zenstruck/browser](https://github.com/zenstruck/browser) that offers a really nice DX to test that kind of things.

In particular, you coul create your own set of Browser Components (like an ImageComponent for instance) to have some custom assert with domain value, easily re-usable along your project tests/pages. 

```php
  // ...    
  ->use(function(ImageComponent $image) {
      $image
          ->assertAltIsDefined()
          ->assertWidth()
         ->assertHeight()
  })
  // ...
```

Using this with the [KernelBrowser](https://github.com/zenstruck/browser?tab=readme-ov-file#kernelbrowser) offers you very good coverage without the hassle of E2E clients, and could fullfill your need :)
