### ISSUE TITLE
Rule idea: named argument syntax

### ISSUE THREAD

**Issue by smnandre** [VincentLanglet/Twig-CS-Fixer#300]
## Context

Twig will [soon support](https://github.com/twigphp/Twig/pull/4209) "colons instead of equals for named arguments" 

Before

```twig
{{ include('foo.html.twig', ignore_missing=true) }}
```

After

```twig
{{ include('foo.html.twig', ignore_missing=true) }}

{# or #}
{{ include('foo.html.twig', ignore_missing: true) }}
```

## New rule ? 

A rule could probably be added to standardize, what should be the default? 

Another rule could maybe simply forbid to different characters in the same expression ?

## Other ones ? 

I guess some other rules may require update (i'm thinking about the rule include filter -> function) ?

**Comment by VincentLanglet** [comment]
The first rule which need to be fixed is the HashQuoteRule or it will transform
```
{{ foo(bar: true) }}
```
into
```
{{ foo('bar': true) }}
```
 

I think the best is to change the Tokenizer to tokenize both `=` and `:` into another tokenType like `NAMED_ARGUMENT_OPERATOR`.

Then:
- HashQuoteRule will be unchanged
- A NamedArgumentSpacingRule could be introduced to add/remove space around this operator.
- A NamedArgumentRule could be introduced to replace all of them by `=` or `:` depending of the preferred value.

> what should be the default?

Not sure we can use `=` by default since it's only supported on last twig version...

**Comment by smnandre** [comment]
> Not sure we can use = by default since it's only supported on last twig version...

You mean `:` right ?

**Comment by VincentLanglet** [comment]
> > Not sure we can use = by default since it's only supported on last twig version...
> 
> You mean `:` right ?

yes, edited

**Comment by VincentLanglet** [comment]
Or we could promote the new `:` syntax but add an early return if it's not supported by Twig (based on the installed version ?)

**Comment by smnandre** [comment]
Let's wait to see how this goes. Personnaly i'm all in to switch to the new syntax, but there may be drawbacks i'm not seeing yet :)

**Comment by VincentLanglet** [comment]
I think I implemented all you wanted in https://github.com/VincentLanglet/Twig-CS-Fixer/pull/302.

I'll just wait for the twig 3.12 release.

**Comment by smnandre** [comment]
>  all you wanted

But i was just conversing, i did not "want" anything 😅 

But that's super great! And i think this will be very useful for a lot of people when 3.12 is released :) 

👏

**Comment by smnandre** [comment]
Well, we have our answer


<img width="865" alt="Capture d’écran 2024-08-17 à 18 35 44" src="https://github.com/user-attachments/assets/e1ea5852-29fc-469a-8429-f297401dee5a">

and

<img width="891" alt="Capture d’écran 2024-08-17 à 18 36 27" src="https://github.com/user-attachments/assets/6733a49c-6e35-4332-aae0-95db11c80882">

**Comment by smnandre** [comment]
So the "characters" are named "separators" in Twig documentation

**Comment by VincentLanglet** [comment]
> <img alt="Capture d’écran 2024-08-17 à 18 36 27" width="891" src="https://private-user-images.githubusercontent.com/1359581/358857580-6733a49c-6e35-4332-aae0-95db11c80882.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTI5NTYsIm5iZiI6MTcyMzkxMjY1NiwicGF0aCI6Ii8xMzU5NTgxLzM1ODg1NzU4MC02NzMzYTQ5Yy02ZTM1LTQzMzItYWFlMC05NWRiMTFjODA4ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTYzNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg5OGZiM2Y2NzMwODgzNjlhMDBkN2EyYTQzZjE5MjUyZmIwNGE1MjIwN2ZjOTFlMzRiZTE5MjAxOTNhOWE1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DTpzewoskrEgxqMQttRmb11j0XPVlZDqIHqm-01JMxY">

Now it's added in the standard, I have to add it to my Twig Standard too.

Not sure about the best strategy:
- Adding the rule without condition, and the rule does nothing for old version of twig
- Adding the rule conditionnaly and the rule throw an error when used with old version of twig

> So the "characters" are named "separators" in Twig documentation

I'll update my naming.

**Comment by smnandre** [comment]
> Adding the rule without condition, and the rule does nothing for old version of twig

Oh you are the most qualified there ;) 

If you want an uneducated & opiniated advice.... i'd do this 
*  add the rule without condition for Twig 4.0 .. 
* disable the rule per default for 3.12 <-> 4.0 and let users chose
* do nothing for Twig < 3.12  (of course ^^)
