### ISSUE TITLE
Bug:  Include tags are incorrectly flagged as failing validation.

### ISSUE THREAD

**Issue by vd-lhridley** [VincentLanglet/Twig-CS-Fixer#304]
### Rule(s) related to or rule(s) missing

[This linting rule is incorrect.](https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/src/Rules/Function/IncludeFunctionRule.php#L25)

Utilizing the include function instead of include tags is a recommendation.  {% include ...%} tags are still perfectly valid in Twig 3.0.

https://twig.symfony.com/doc/3.x/tags/include.html

### Expected behavior

This is not a requirement, it is a recommendation.

### Actual behavior

This rule is a requirement.

**Comment by VincentLanglet** [comment]
This is not a bug, but an opinionated standard, as explained in the doc.

> By default, the twig-cs-fixer standard is enabled with the twig coding standard rules and some extra rules.

You can use the configuration file to disable some rules or add extra one (or use a different standard) 
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/docs/configuration.md#configuration-file

```
$ruleset = new TwigCsFixer\Ruleset\Ruleset();

// You can start from a default standard
$ruleset->addStandard(new TwigCsFixer\Standard\TwigCsFixer());
// Or new TwigCsFixer\Standard\Twig() if you want less rules.

// And then add/remove/override some rules
$ruleset->removeRule(TwigCsFixer\Rules\Function\IncludeFunctionRule::class);

$config = new TwigCsFixer\Config\Config();
$config->setRuleset($ruleset);

return $config;
```
