### ISSUE TITLE
Feature request:   Allow classing rules as errors, warnings, etc.

### ISSUE THREAD

**Issue by vd-lhridley** [VincentLanglet/Twig-CS-Fixer#305]
### Rule(s) related to or rule(s) missing

Not all rules in the ruleset are definite errors, some are recommendations.  This linter does not differentiate between the two.

It would be great if "recommendations" could be classed as "warnings" instead of "errors", and subsequently be able to filter the reported output to errors only.

[friendsoftwig/twigcs](https://github.com/friendsoftwig/twigcs) supports [this functionality](https://github.com/friendsoftwig/twigcs?tab=readme-ov-file#restricting-output).

**Comment by VincentLanglet** [comment]
> Not all rules in the ruleset are definite errors, some are recommendations. This linter does not differentiate between the two.
> It would be great if "recommendations" could be classed as "warnings" instead of "errors", and subsequently be able to filter the reported output to errors only.

Changing a severity report in order to filter out such error is basically the same than just "removing/ignoring the rule".
This feature already exists. See https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/docs/configuration.md#configuration-file and https://github.com/VincentLanglet/Twig-CS-Fixer/issues/304#issuecomment-2301260287

**Comment by smnandre** [comment]
I was wondering, @vd-lhridley .. as you have a better knowledge than us (than me at least, don't want to speak in place of @VincentLanglet ..) .. would you maybe help creating a "Drupal" ruleset ?

**Comment by VincentLanglet** [comment]
I consider https://github.com/VincentLanglet/Twig-CS-Fixer/issues/305#issuecomment-2301262256 comment closed the issue
