### ISSUE TITLE
!== and === gets changed to broken syntax

### ISSUE THREAD

**Issue by M-arcus** [VincentLanglet/Twig-CS-Fixer#315]
### Rule(s) related to or rule(s) missing

`TwigCsFixer\Rules\Operator\OperatorSpacingRule`

`{% set myBoolVariableAssignment = myVar !== false and myOther === 'myString' %}`

### Expected behavior

`{% set myBoolVariableAssignment = myVar is same as(false) and myOther is same as('myString') %}`

### Actual behavior

`{% set myBoolVariableAssignment = myVar != = false and myOther == = 'myString' %}`

**Comment by M-arcus** [comment]
Thank you for the quick reply!
Weird, it never broke the output of the rendering, maybe because my twig installation is running on an older version.
Closing this issue as completed.

**Comment by VincentLanglet** [comment]
Do you mean that
```
{% set myBoolVariableAssignment = myVar !== false and myOther === 'myString' %}
```
is valid and working on your side ?

Do you use Symfony/twig or something else like Drupal/... ?
Do you have defined custom operators ?

**Comment by M-arcus** [comment]
No, it's not valid, but it didn't throw an exception. It's an old shopware/shopware installation

**Comment by VincentLanglet** [comment]
Shopware defines this as custom operator cf https://github.com/shopware/shopware/blob/f7726383def46c51d62a3d5fde57eb53c084ab11/src/Core/Framework/Adapter/Twig/Extension/PhpSyntaxExtension.php#L180-L182

In order for TwigCsFixer to be aware of, it requires to follow to use a config file with https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/docs/configuration.md#token-parsers--more

$config = new TwigCsFixer\Config\Config();
$config->addTwigExtension(new Shopware\Core\Framework\Adapter\Twig\Extension\PhpSyntaxExtension());

**Comment by M-arcus** [comment]
This works fine with 
```php
$config->addTwigExtension(new Shopware\Core\Framework\Adapter\Twig\Extension\PhpSyntaxExtension());
```
but not with 
```php
$config->addTwigExtension(new Shopware\Core\Framework\Adapter\Twig\Extension\BuildBreadcrumbExtension());`
```
because `BuildBreadcrumbExtension` needs injects:
```php
public function __construct(
  private readonly CategoryBreadcrumbBuilder $categoryBreadcrumbBuilder,
  private readonly EntityRepository $categoryRepository
) {
}
```
Is there a possibility to inject these somehow?

**Comment by VincentLanglet** [comment]
You dont have to inject every twigExtension, only the one with the custom operator,
so 
```
$config->addTwigExtension(new Shopware\Core\Framework\Adapter\Twig\Extension\PhpSyntaxExtension());
```
is enough.
