### ISSUE TITLE
TrailingCommaMultiLineRule not included by default

### ISSUE THREAD

**Issue by joncjordan** [VincentLanglet/Twig-CS-Fixer#320]
### Rule(s) related to or rule(s) missing

TrailingCommaMultiLineRule

### Expected behavior

The documentation states that `TrailingCommaMultiLineRule` is included by default, but it doesn't seem to be the case. If you look at \TwigCsFixer\Standard\TwigCsFixer it includes TrailingCommaSingleLineRule but not TrailingCommaMultiLineRule. 

### Actual behavior

I had to add the .twig-cs-fixer.php file to get this working properly, otherwise this rule was not being applied.

```
<?php

$ruleset = new TwigCsFixer\Ruleset\Ruleset();
$ruleset->addStandard(new TwigCsFixer\Standard\TwigCsFixer());

// And then add/remove/override some rules
$ruleset->addRule(new TwigCsFixer\Rules\Punctuation\TrailingCommaMultiLineRule());

$config = new TwigCsFixer\Config\Config();
$config->setRuleset($ruleset);

return $config;
```

**Comment by joncjordan** [comment]
Hmm I guess this is where it was removed from the standard rules:
https://github.com/VincentLanglet/Twig-CS-Fixer/pull/259

Any plans for re-adding it?

**Comment by VincentLanglet** [comment]
The rule wasn't working properly on 2.x version and I had to make some changes in 3.x https://github.com/VincentLanglet/Twig-CS-Fixer/pull/265 to fix the bugs.
- https://github.com/VincentLanglet/Twig-CS-Fixer/issues/257
- https://github.com/VincentLanglet/Twig-CS-Fixer/issues/256

But sure, I'm opened to adding back this rule.

I didn't have time yet to try it on my personal work codebase. Does it work correctly for you (on a huge codebase ?)

 Can you do the PR to add it back ? :)

**Comment by joncjordan** [comment]
I wouldn't say my codebase is _huge_ but I tested it against 175+ files and didn't experience any issues with it, and it fixed all my trailing comma issues in multi-line arrays. But I'm not sure I have any examples of where the bug was produced previously...
