### ISSUE TITLE
CannotTokenizeException: Unexpected character ":" when using new `{% types %}` block

### ISSUE THREAD

**Issue by ruudk** [VincentLanglet/Twig-CS-Fixer#330]
There seems to be a problem with the new `{% types %}` block introduced in:
- https://github.com/VincentLanglet/Twig-CS-Fixer/pull/323

It only happens in specific cases. I was able to reproduce it:

```twig
{% types {
  entity: 'App\Entity',
%}

{% block main %}
    Status:
{% endblock %}
```

Results in:
```
TwigCsFixer\Exception\CannotTokenizeException: Unexpected character ":" at line 6.
/Volumes/CS/opensource/Twig-CS-Fixer/src/Exception/CannotTokenizeException.php:26
/Volumes/CS/opensource/Twig-CS-Fixer/src/Token/Tokenizer.php:703
/Volumes/CS/opensource/Twig-CS-Fixer/src/Token/Tokenizer.php:339
/Volumes/CS/opensource/Twig-CS-Fixer/src/Token/Tokenizer.php:363
/Volumes/CS/opensource/Twig-CS-Fixer/src/Token/Tokenizer.php:119
/Volumes/CS/opensource/Twig-CS-Fixer/tests/Token/Tokenizer/TokenizerTest.php:142
```

When I remove the `:` after Status, the error goes away.

If I change the `:` to `&` I get the following error:
```
TwigCsFixer\Exception\CannotTokenizeException: Unexpected character "&" at line 6.
```

So something is going wrong here. Not sure what.

**Comment by ruudk** [comment]
Wow, silly me. I did not close the types tag 🤦 

Completely overlooked this.

**Comment by ruudk** [comment]
Solved with:
```twig
{% types {
  entity: 'App\Entity',
} %}

{% block main %}
    Status:
{% endblock %}
```

Question: should Twig CS Fixer warn me about this mistake 😁

**Comment by VincentLanglet** [comment]
> Question: should Twig CS Fixer warn me about this mistake 😁

You already have an error when executing your twig no ?
I only lint correctly valid twig.

But I wonder if twig already fail with
```
{% types {entity: 'App\Entity', %}
```
maybe I should fail as soon as I see `%)`

**Comment by ruudk** [comment]
Well, I did not execute this, because this is a meta tag, that doesn't do anything there. So in this particular case, it did not even occur to me to try it in the browser. 

Given that Twig CS Fixer is also a linter that warns for errors, I think it would be great if it could give a better hint to the problem. In this case, I did not understand it because the error was far away from my types tag.

**Comment by ruudk** [comment]
> maybe I should fail as soon as I see `%}`

Yes indeed. From that point on, you know the tag is closed, but the content is invalid.

**Comment by VincentLanglet** [comment]
Logic is in Tokenizer::lexBlock and Tokenizer::lexVar.

It's not "that" easy cause 
```
{{ {bar: {foo: baz}} }}
```
I should not detect the first `}}` as closing the var tag.

That's why I only start to look for closer when there is no bracket opened. (and twig does the same).

So 
```
{{ {bar:  }}
```
would not be easy to be soon detected

Maybe it could be "just" check for block
```
{% if {bar: %} %}
```
but it means the first `%}` should not be detected as the closing one.

**Comment by ruudk** [comment]
> {% if {bar: %} %}


This is not valid anyway, right?

**Comment by ruudk** [comment]
Ok. 

I have Twig CS Fixer set-up on save in PHPStorm. So it immediately picks up errors.
