### ISSUE TITLE
Add support for inline comments

### ISSUE THREAD

**Issue by seb-jean** [VincentLanglet/Twig-CS-Fixer#339]
Hi,

It would be nice to add the rule for:
https://github.com/twigphp/Twig/pull/4349

I have an error:
`Unable to tokenize file: Unexpected character "#" at line`

Thanks!

**Comment by VincentLanglet** [comment]
Could you try the PR https://github.com/VincentLanglet/Twig-CS-Fixer/pull/341 ?

Does it work for all your inline comments ?
