### ISSUE TITLE
Twig for-if upgrade rule

### ISSUE THREAD

**Issue by jaapio** [VincentLanglet/Twig-CS-Fixer#344]
Hi, 

Thanks for this amazing tool. It saved me a couple of hours of poor copy past work. 
I was upgrading phpDocumentor to twig 3. And came across an deprecation in twig 2. So I started implementing a rule that would fix this. It's not perfect but it helped me to upgrade. 

If you want, I can improve the code and add some test so it can be part of this project. 

### Problem

```diff
- {% for tagName, tags in node.tags if tagName in ['link', 'see']) %}
+ {% for tagName, tags in node.tags|filter (tagName =>  tagName in ['link', 'see']) %}
{% endfor %}
```   

### The rule

```php
final class ForIfRule extends AbstractFixableRule
{
    protected function process(int $tokenIndex, Tokens $tokens): void
    {
        $token = $tokens->get($tokenIndex);
        if ($token->getValue() !== 'for') {
            return;
        }

        if ($token->getType() !== Token::BLOCK_NAME_TYPE) {
            return;
        }

        $ifTokenIndex = null;
        $fixer = null;
        foreach ($tokens->toArray() as $index => $token) {
            if ($index <= $tokenIndex) {
                continue;
            }

            // We found the end of the for block
            if ($token->isMatching([Token::BLOCK_END_TYPE])) {
                return;
            }

            if ($token->getValue() !== 'if') {
                continue;
            }

            $fixer = $this->addFixableError('If statement inside for loop is not allowed', $token);
            if ($fixer === null) {
                return;
            }

            $ifTokenIndex = $index;

            break;
        }

        if ($fixer === null || $ifTokenIndex === null) {
            return;
        }

        $endBlock = $tokens->findNext(Token::BLOCK_END_TYPE, $tokenIndex);

        $nameIndex = $tokens->findNext(Token::NAME_TYPE, $ifTokenIndex + 1, $endBlock);
        if ($nameIndex === null) {
            return;
        }

        $fixer->beginChangeSet();
        $fixer->addContentBefore($ifTokenIndex, '|');
        $fixer->replaceToken($ifTokenIndex, sprintf(' | filter (%s => ', $tokens->get($nameIndex)->getValue()));
        $fixer->addContentBefore($endBlock, ')');
        $fixer->endChangeSet();
    }
}
```

**Comment by VincentLanglet** [comment]
> It's not perfect but it helped me to upgrade.

Do you mean there is for-if cases where it will break the code ? or does the replacement
```
for A in B if C
for A, B in C if D
```
to
```
for A in B | filter(A => C)
for A, B in C | filter(A => D)
```
always works ?

**Comment by jaapio** [comment]
I noticed that my code had some more complex if statements where it didn't work. But 99% of the refactoring was done perfectly. 

The issue was caused by a case that used an extra variable. `if foo.bar == extra.param` 

Extra could not be found in the filter.

**Comment by VincentLanglet** [comment]
> I noticed that my code had some more complex if statements where it didn't work. But 99% of the refactoring was done perfectly.
> 
> The issue was caused by a case that used an extra variable. `if foo.bar == extra.param`
> 
> Extra could not be found in the filter.

Do you have an example ?

Because if I understand correctly, this should be something like
```
{% set b = 1 %}
{% for i in [1, 2]|filter(a => a == b) %}
  {{ i }}
{%endfor %}
```

But this seems to works well
https://twig.symfony.com/play?data=eyJ0ZW1wbGF0ZXMiOltbImluZGV4LnR3aWciLCJ7JSBzZXQgYiA9IDEgJX1cbnslIGZvciBpIGluIFsxLCAyXXxmaWx0ZXIoYSA9PiBhID09IGIpICV9XG4gIHt7IGkgfX1cbnslZW5kZm9yICV9Il1dLCJjb250ZXh0Ijp7Im5hbWUiOiJXb3JsZCJ9LCJ2ZXJzaW9uIjoiMy4xNy4xIiwib3B0aW9ucyI6eyJzdHJpY3RfdmFyaWFibGVzIjp0cnVlLCJjaGFyc2V0IjoiVVRGLTgiLCJhdXRvZXNjYXBlIjoiIn19
 
> But apart from that it works, so if you want I can create a pr. To get this extra rule in the application.

If we can have a rule working on 100% of the case, adding it could be great.
But if there is cases which cannot be handle I don't want to provide a rule which might break code.

**Comment by VincentLanglet** [comment]
Anyway, I just saw I require twig 3 to use this linter, so there is no benefit adding this rule on the current version.
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/composer.json#L21
