### ISSUE TITLE
Question on some twig cs fix

### ISSUE THREAD

**Issue by noniagriconomie** [VincentLanglet/Twig-CS-Fixer#36]
Hi, first thanks for this lib, I discovered it recently and began to use it on some of my pro/perso projects :)

### Rule(s) related to or rule(s) missing

I have a question regarding a fix on spaces for some twig: see after

### Expected behavior

**it removes extra spaces**

```
{% extends '@Admin/base.html.twig' %}
{% block main_content %}
```

### Actual behavior

**it does not remove extra spaces**

```
{%    extends    '@Admin/...'     %}
{%    block main_content       %}
```

---

I was expecting the same twig cs fix as for example:

`{{  my_var}}` => `{{ my_var }}`

---

Is it a normal behavior or should I configure something?
I am using the v0.3 with the default config (and twig/twig v2)

Thank you!

**Comment by VincentLanglet** [comment]
It's supposed to remove/add the extra/missing space and worked fine for me.
At first sigh, I would say you don't use it correctly.
```
bin/twig-cs-fixer lint --fix /path/to/code
```

**Comment by noniagriconomie** [comment]
@VincentLanglet Apologies!

🤦‍♂️ I was fixing a file A but checking file B
And my IDE took time also to notice the fixes

So far so good, thx! 😃

**Comment by VincentLanglet** [comment]
No problem.
And if you like this library dont forget to star it :)

**Comment by noniagriconomie** [comment]
Lucky I have 2 accounts 😄 🌟
