### ISSUE TITLE
Comparison to friendsoftwig/twigcs

### ISSUE THREAD

**Issue by adamzimmermann** [VincentLanglet/Twig-CS-Fixer#4]
Can you help me understand how this relates to https://github.com/friendsoftwig/twigcs with functionality and when I would want to use one vs the other?

The one big thing I've noticed so far is that this project seems to offer automated code style fixes while https://github.com/friendsoftwig/twigcs [does not](https://github.com/friendsoftwig/twigcs/issues/33).

This project also seems to enforce the Symfony standard while https://github.com/friendsoftwig/twigcs enforces the "Official one from Twig".

> At the moment the only available standard is the official one from twig.

- https://github.com/friendsoftwig/twigcs#custom-coding-standard

I need to test them both out more this week, but wanted to file an issue to hopefully get a discussion started and document my finding too when I know more.

Any help or guidance is much appreciated!

**Comment by VincentLanglet** [comment]
Like you noticed it one of the main difference between https://github.com/friendsoftwig/twigcs and this library is the fixer I wrote. If you need a fixer, I'm not sure another library has this feature.

Also the rules are different.
I cannot access to http://twig.sensiolabs.org/doc/coding_standards.html, the url provided by friendsoftwig/twigcs, but looking at the implemented rules:
- Unused macro and variable are reported. IMHO, this is not the job of a linter.
- Trailing space are reported. I'm not sure I have this rule ; I could.
- Variable need to be lower case for set/for ; I plan to add this rule but I wanted more explanation before https://github.com/twigphp/Twig/issues/3545
- Syntax error I reported (if I understand the RegEngineRule). I use twig directly for those checks.

In my case you'll have a better integration of the standard https://twig.symfony.com/doc/3.x/coding_standards.html ; the number of space before and after every operators, brackets, parenthesis, delimiter, ... will be checks.
So it seems more complete to me

**Comment by adamzimmermann** [comment]
Thank you for the quick detailed response!

---

> Like you noticed it one of the main difference between friendsoftwig/twigcs and this library is the fixer I wrote. If you need a fixer, I'm not sure another library has this feature.

I did find https://github.com/trivago/prettier-plugin-twig-melody, but it uses Yarn instead of Composer. So likely targeted at a different audience.

---

> I cannot access to http://twig.sensiolabs.org/doc/coding_standards.html, the url provided by friendsoftwig/twigcs, but looking at the implemented rules:

I can't access that either. I'm not sure what is going on.

---

> Syntax error I reported (if I understand the RegEngineRule). I use twig directly for those checks.

I found Symfony tools that seem to do this too. https://github.com/symfony/symfony/blob/v3.3.9/src/Symfony/Bridge/Twig/Command/LintCommand.php

--

FWIW this is largely motivated by a desire to have an official recommendation for Drupal. I am working with @markdorison on getting a consensus going:
- https://www.drupal.org/project/coder/issues/2657704
  - The answer here might be that Coder should not handle it and we use a tool such as yours.
- https://www.drupal.org/docs/develop/coding-standards/twig-coding-standards
  - This page also references the broken Sensio Labs page. 🤷🏼 

I would love to add additional rules in a separate ruleset for Drupal specific linting that extend your work too at some point if needed.

I'm planning to test this tool on several repos in the next couple days and I'll report back.

---

Thanks for creating this tool and for the quick response.

**Comment by VincentLanglet** [comment]
I were using a php linter for my work project, with custom rules:
https://github.com/VincentLanglet/symfony-custom-coding-standard
And didn't find satisfying similar twig linter/fixer so I wrote mine.

I just split it from the previous repository recently, but I use it for 2 years now.

> I would love to add additional rules in a separate ruleset for Drupal specific linting that extend your work too at some point if needed.
> 
> I'm planning to test this tool on several repos in the next couple days and I'll report back.

Sure ! Contributions are welcomed ; we can talk about new rules.

If you like this repository, don't forget to star :)

**Comment by adamzimmermann** [comment]
I've referenced this project in my discussion here:

- https://www.drupal.org/project/coder/issues/2657704

Hopefully this conversation gains some traction as it would be great to have a tool like this in place with Drupal. 🤞🏼

**Comment by VincentLanglet** [comment]
Thanks for the visibility.

> Just released with the past month or so.

For the record, the repository is just released, but was in another repository before: https://github.com/VincentLanglet/symfony-custom-coding-standard/releases/tag/6.1.0
and removed https://github.com/VincentLanglet/symfony-custom-coding-standard/releases/tag/9.0.0

It's been two years we're using it at my work project.
There is currently not a lot of feature because we were the only users.
But at least I can say we fixed all the bugs encountered ^^'

**Comment by adamzimmermann** [comment]
Ah thanks for that context. I'll update my comment there.

**Comment by VincentLanglet** [comment]
Closing, as question was answered
