### ISSUE TITLE
Check HTML codestyle in twig files 

### ISSUE THREAD

**Issue by mrtronje** [VincentLanglet/Twig-CS-Fixer#43]
Hi

Thanks for your efforts to make a cs-fixer for Twig - it works very well! 

Are there any plans to check also HTML codestyle? Because in most cases Twig files consist of a lot of HTML code and it would be cool if this would be checked too :-)

**Comment by VincentLanglet** [comment]
> Are there any plans to check also HTML codestyle? Because in most cases Twig files consist of a lot of HTML code and it would be cool if this would be checked too :-)

Hi, which html codestyle do you have in mind ?

I should check again but I think the linter is parsing `<div><div>foo</div></div>` as a single Token text.
So I would say this could be complicated to correctly understand the html.
