### ISSUE TITLE
fail to lint this : {% for a in b.in %}

### ISSUE THREAD

**Issue by rafipiccolo** [VincentLanglet/Twig-CS-Fixer#49]
when i run twigcsfixer on this particular file it fails

the run
```
twig-cs-fixer lint --fix test.html.twig 
Error: Cannot fix the file "test.html.twig".
```

the file
```
{% for a in b.in %}
    <tr>
    </tr>
{% endfor %}
```

".in" is causing twig-cs-fixer to fail. when i rename this to "ins" for exemple the code is ok.

**Comment by VincentLanglet** [comment]
Should be solved in the version 0.4.4
