### ISSUE TITLE
Add a sniff (test case) for formatting of self-closing HTML tags

### ISSUE THREAD

**Issue by ndf** [VincentLanglet/Twig-CS-Fixer#57]
### Rule(s) related to or rule(s) missing

Imagine this Twig:

```
<hr     />
<hr />
<hr/>
```

### Expected behavior

It would be helpful if the linter would error on 2 of the 3 examples.
And standardize on the formatting of self-closing HTML tags.

NB My phpstorm makes it `<hr/>`

### Actual behavior

Linter does not check formatting of self-closing tags.

**Comment by VincentLanglet** [comment]
Hi, thank for your suggestion.

This would be the job of an html fixer, and not the twig-cs-fixer IMHO.

You can use twig for non-html files.
There is a lot of examples here: https://github.com/sonata-project/dev-kit/tree/master/templates/project
What if someone use a `twig` on a `.txt.twig` file and use `<hr />` in his code ?

Also, currently the tokenizer of this project is parsing only the twig-related code, everything else is considered as `text`, which means that:
```
<div>foo</div><hr /><div>bar</div>
```
is just a single string `'<div>foo</div><hr /><div>bar</div>'`.
