### ISSUE TITLE
Inability to include "&" in a translatable string without an error

### ISSUE THREAD

**Issue by adamzimmermann** [VincentLanglet/Twig-CS-Fixer#6]
### Rule(s) related to or rule(s) missing

https://github.com/VincentLanglet/Twig-CS-Fixer/blob/0ff9c02f136856ef708bde0a309758d39f3bba08/src/Token/Tokenizer.php#L386

It seems that we need to add an additional `ifelse` statement to catch a translation block.

Or assuming that this is a `block`, perhaps this logic needs to be updated?

https://github.com/VincentLanglet/Twig-CS-Fixer/blob/0ff9c02f136856ef708bde0a309758d39f3bba08/src/Token/Tokenizer.php#L395-L408

I'm happy to submit a patch if you can nudge me in the right direction.

### Expected behavior

Users are able to include `&` in a translated string with this flagging it as an issue. I'm presuming this might be a bug for other characters as well.

### Actual behavior

Template file:

```
{#
/**
 * @file
 * HTML for the copyright notice.
 */
#}

{% set year = "now"|date("Y") %}

<div class="structure__copyright">
  {% trans with {
    '%privacy_path%': path('entity.node.canonical', {'node': 309}),
    '%terms_path': path('entity.node.canonical', {'node': 308}),
    '%year': year
  %}
    I want to translate text about this & that.
  {% endtrans %}
</div>

```
Command line output:

```
 [ExecStack] Executing vendor/bin/twig-cs-fixer lint web/modules/custom web/themes/example
 [ExecStack] Running vendor/bin/twig-cs-fixer lint web/modules/custom web/themes/example

 KO /Users/example/www/example/web/modules/custom/example_module/templates/example-copyright-block.html.twig
 ------- ------------------------------------------------------
  FATAL   15   | %}
          16   |   I want to translate text about this & that.
          >>   | Unexpected character "&".
          17   | {% endtrans %}
 ------- ------------------------------------------------------


 [ERROR] Files linted: 118, notices: 0, warnings: 0, errors: 1


 [ExecStack]  Exit code 1  Time 1.858s
 [notice] Stopping on fail. Exiting....
 [error]  Exit Code: 1
 [error]    in task Robo\Task\Base\ExecStack


Script robo --ansi handling the robo event returned with error code 1
Script composer robo job:check-coding-standards handling the cs-check event returned with error code 1
```

**Comment by VincentLanglet** [comment]
Hi @adamzimmermann, I'm curious, is your twig working in your application ?

Does the linter works better if you add `}` before closing the block ?
```
{% trans with {
    '%privacy_path%': path('entity.node.canonical', {'node': 309}),
    '%terms_path': path('entity.node.canonical', {'node': 308}),
    '%year': year
} %}
```

**Comment by adamzimmermann** [comment]
Wow, totally missed that. My bad. 🤦🏼 Thanks for catching that.

That solved it! 🎉
