### ISSUE TITLE
fail to lint string slice notation

### ISSUE THREAD

**Issue by sirchris** [VincentLanglet/Twig-CS-Fixer#75]
Let's say we have sth like this in the code:
`{% set var = 'test'[0:1] ~ 'test'[:3] %}`

After firing the `lint --fix` we have:
`{% set var = 'test'[0: 1] ~ 'test'[: 3] %}`

![image](https://user-images.githubusercontent.com/6849214/199698334-6cf01cac-c689-4ed1-9941-311cc0142eef.png)

**Comment by VincentLanglet** [comment]
Hi ! Can you try https://github.com/VincentLanglet/Twig-CS-Fixer/pull/77 @sirchris

Also, do you know if the `:` symbol is used for something else than
- Ternary: `$foo ? 1 : 2` or `$foo ?: 1`
- Object: `{a: 1, b: 2}`
- Slice: `[1:2]`
?

**Comment by sirchris** [comment]
Yep, it's working fine now. And it seems that all use cases are covered 👍

**Comment by VincentLanglet** [comment]
I'll release this as soon as I've tested the new cache feature.
