### ISSUE TITLE
Space in single line objects

### ISSUE THREAD

**Issue by alexander-schranz** [VincentLanglet/Twig-CS-Fixer#91]
### Rule(s) related to or rule(s) missing

I'm searching for a way which I can force a space around object in single lines.

### Expected behavior

```diff
+{{ include('app/atoms/icon.html.twig', { icon: 'time' }, with_context = false) }
-{{ include('app/atoms/icon.html.twig', {icon: 'time'}, with_context = false) }}
```

### Actual behavior

```diff
-{{ include('app/atoms/icon.html.twig', { icon: 'time' }, with_context = false) }
+{{ include('app/atoms/icon.html.twig', {icon: 'time'}, with_context = false) }}
```

**Comment by VincentLanglet** [comment]
This was developed to follow the twig standard https://twig.symfony.com/doc/3.x/coding_standards.html
With the following example `{{ {'foo': 'bar'} }}`.

But it should be able to configure this with some development.
Currently the check is made by this Sniff: https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/src/Sniff/PunctuationSpacingSniff.php

The idea would be to configure it like this:
```
$ruleset = new TwigCsFixer\Ruleset\Ruleset();
$ruleset->addStandard(new TwigCsFixer\Standard\Generic());
$ruleset->addSniff(new TwigCsFixer\Sniff\PunctuationSpacingSniff([
    'before' => ['}' => 1],
    'after' => ['{' => 1],
]));
```
or
```
$ruleset = new TwigCsFixer\Ruleset\Ruleset();
$ruleset->addStandard(new TwigCsFixer\Standard\Generic());
$ruleset->addSniff(new TwigCsFixer\Sniff\PunctuationSpacingSniff([
    '}' => ['before' => 1],
    '{' => ['after' => 1],
]));
```
or another syntax (I dunno which one is the best).

WDYT about this solution ?

**Comment by alexander-schranz** [comment]
The configuration looks good but I'm not sure if we run into problems with single vs multi line or how we can handle that:

```twig
{{ include('app/atoms/icon.html.twig', { icon: 'time' }, with_context = false) }
```

vs.

```twig
{{ include('app/atoms/icon.html.twig', {
    icon: 'time',
    space: '20',
}, with_context = false) }}
```

**Comment by VincentLanglet** [comment]
> ```
> {{ include('app/atoms/icon.html.twig', {
>     icon: 'time',
>     space: '20',
> }, with_context = false) }}
> ```

There is already the check
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/src/Sniff/AbstractSpacingSniff.php#L45-L49
"If the next token is a new line, do nothing".

And
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/src/Sniff/AbstractSpacingSniff.php#L85-L89
"If the previous token is a new line, do nothing".

So it shouldn't be an issue.

**Comment by alexander-schranz** [comment]
Also a little hint to the twig internals. Twig allow to be customized the tags: https://twig.symfony.com/doc/3.x/recipes.html#customizing-the-syntax. I'm not sure if you are using the twig lexer, twig parser, if we should use the `Token` constants of Twig itself so the cs fixer could be used with customized things. https://github.com/twigphp/Twig/blob/b5ec7ab1cdfebf3e0ab0a5fddc342dbd903763fa/src/Token.php#L34

> So it shouldn't be an issue.

That looks great 👍

**Comment by VincentLanglet** [comment]
> Also a little hint to the twig internals. Twig allow to be customized the tags: https://twig.symfony.com/doc/3.x/recipes.html#customizing-the-syntax. I'm not sure if you are using the twig lexer, twig parser, if we should use the `Token` constants of Twig itself so the cs fixer could be able to understand custom syntax. https://github.com/twigphp/Twig/blob/b5ec7ab1cdfebf3e0ab0a5fddc342dbd903763fa/src/Token.php#L34

I use my own constant, but some of them are Twig-based
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/src/Token/Token.php#L12-L39

And my Lexer is more complex than, but similar to, the Twig one
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/src/Token/Tokenizer.php#L16

And currently I would say it doesn't work if `{{`, `{#`,  `{%` are not used.

> > So it shouldn't be an issue.
> 
> That looks great 👍

Do you want to try a PR ?

I would say the best conf could be one array for the Before, one array for the after.
```
// What you want
$ruleset->addSniff(new TwigCsFixer\Sniff\PunctuationSpacingSniff(
    ['}' => 1],
    ['{' => 1],
));
// Another way to use it
$ruleset->addSniff(new TwigCsFixer\Sniff\PunctuationSpacingSniff(
    ['}' => 1, ']' => 1],
    ['{' => 1, '[' => 1],
));
// A way to disable check for `{` and `}`
$ruleset->addSniff(new TwigCsFixer\Sniff\PunctuationSpacingSniff(
    ['}' => null],
    ['{' => null]
));
```

**Comment by alexander-schranz** [comment]
@VincentLanglet I will try it at the weekend maybe. If somebody else want to implement before me, they can feel free todo it :)

**Comment by VincentLanglet** [comment]
> @VincentLanglet I will try it at the weekend maybe. If somebody else want to implement before me, they can feel free todo it :)

Ping me if you need help

**Comment by VincentLanglet** [comment]
I made something if you wanna try https://github.com/VincentLanglet/Twig-CS-Fixer/pull/92 @alexander-schranz

**Comment by alexander-schranz** [comment]
@VincentLanglet the rule itself works like expected. I found one little edge case which is an empty object:

```
-{%- set additionalAttributes = attr|default({})|aria_data_attributes -%}
+{%- set additionalAttributes = attr|default({ })|aria_data_attributes -%}
```

I did just stumble over the `cache`. I think it would be great that the cache is not longer valid when:

 - A new twig-cs-fixer version is installed
 - The ruleset is changed, or ruleset options are changed

As the ruleset was not applied to all files instead only the files I changed since last run.

**Comment by VincentLanglet** [comment]
> @VincentLanglet the rule itself works like expected. I found one little edge case which is an empty object:
> 
> ```
> -{%- set additionalAttributes = attr|default({})|aria_data_attributes -%}
> +{%- set additionalAttributes = attr|default({ })|aria_data_attributes -%}
> ```

I'm not sure how to solve this.
With the config changes, the rule is literally asking for one space after `{`, and one space before `}`.
It seems not easy to add configurable special cases.

> I did just stumble over the `cache`. I think it would be great that the cache is not longer valid when:
> 
> * A new twig-cs-fixer version is installed
> * The ruleset is changed, or ruleset options are changed
> 
> As the ruleset was not applied to all files instead only the files I changed since last run.

Will take a look

**Comment by alexander-schranz** [comment]
@VincentLanglet not sure if I would complicate it to much and make currently just `1` given into that rule e.g.: `new TwigCsFixer\Sniff\PunctuationSpacingSnif` and keep the other things currently as defaults aslong as no more options are really required or requested by others.

**Comment by VincentLanglet** [comment]
The issue with
```
new TwigCsFixer\Sniff\PunctuationSpacingSnif(space: 1)
```
is that `PunctuationSpacingSnif` is working with every punctuation
```
private const SPACE_BEFORE = [
        ')' => 0,
        ']' => 0,
        '}' => 0,
        ':' => 0,
        '.' => 0,
        ',' => 0,
        '|' => 0,
    ];
    private const SPACE_AFTER = [
        '(' => 0,
        '[' => 0,
        '{' => 0,
        '.' => 0,
        '|' => 0,
        ':' => 1,
        ',' => 1,
    ];
```

So if you just give `space: 1` it will override every token...
That's why I wanted to find something per token.
